baseURL = "https://www.bryansebesta.blog/"
languageCode = "en-us"
title = "Bryan Sebesta's Digital Garden"
copyright = "© Copyright 2021 Bryan Sebesta"

sectionPagesMenu = "main"



[params]
  Author = "Bryan Sebesta"
  Description = "The digital garden of Bryan Sebesta"

[taxonomies]
  category = "categories"
  tag = "tags"